# Generated by Django 3.0.5 on 2020-04-05 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotels',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('location', models.IntegerField(choices=[(1, 'Pune'), (2, 'Mohali'), (3, 'Punjab'), (4, 'Delhi')])),
                ('email', models.EmailField(max_length=254, null=True)),
                ('Star', models.IntegerField(choices=[(1, '1 Star'), (2, '2 Star'), (3, '3 Star'), (4, '4 Star'), (5, '5 Star'), (6, '0 Star')])),
            ],
        ),
    ]
