# Generated by Django 3.0.5 on 2020-04-05 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hotels', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotels',
            old_name='Star',
            new_name='star',
        ),
    ]
