# Generated by Django 3.0.5 on 2020-04-05 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotels', '0002_auto_20200405_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotels',
            name='location',
            field=models.IntegerField(choices=[('Pune', '1'), ('Mohali', '2'), ('Punjab', '3'), ('Delhi', '4')]),
        ),
    ]
